START TRANSACTION;
CREATE TABLE `ResetPassword` (
	`ID` INT AUTO_INCREMENT NOT NULL,
	`UserID` INT NOT NULL,
	`ResetCode` CHAR ( 64 ) NOT NULL,
	`Time` datetime DEFAULT CURRENT_TIMESTAMP NOT NULL ,
	UNIQUE INDEX ( `UserID` ),
    FOREIGN KEY (`UserID`) REFERENCES `User` (`ID`),
	PRIMARY KEY ( `ID` ) 
) ;
COMMIT;