START TRANSACTION;
CREATE TABLE `Image` (
	`ID` INT AUTO_INCREMENT NOT NULL,
	`UserID` INT NOT NULL,
	`ImgHash` CHAR ( 64 ) NOT NULL,
    /*这个字段应该用不到
	`ImgPath` TEXT NOT NULL,*/
    `Height` INT UNSIGNED NOT NULL,
    `Width` INT UNSIGNED NOT NULL,
    `Size` INT UNSIGNED NOT NULL,
    `Count` INT UNSIGNED DEFAULT 0 NULL,
	`Time` datetime DEFAULT CURRENT_TIMESTAMP NOT NULL ,
    FOREIGN KEY (`UserID`) REFERENCES `User` (`ID`),
    UNIQUE INDEX (`UserID`, `ImgHash`),
	PRIMARY KEY ( `ID` ) 
) ;
COMMIT;
